FROM openjdk:13-alpine

ENV TZ=Australia/Melbourne

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apk add --update --no-cache py-pip docker

RUN pip --no-cache-dir install --upgrade awscli