steps:
  - label: 'Run unit tests :unicorn_face:'
    command: sh ./ops/bin/test.sh
    branches: 'master'
    agents:
      queue: fma-dev-dflt
  - wait
  - label: 'Build and publish docker image :docker:'
    command: sh ./ops/bin/build.sh
    branches: 'master'
    agents:
      queue: fma-dev-dflt
  - wait
  - label: 'Deploy to Europa Preprod :chrome:'
    command: sh ./ops/bin/deploy.sh
    branches: 'master'
    agents:
      queue: europa-preprod-training
